export const PRIMARY: string = '#1A5277'
export const WHITE: string = 'white'
export const SECONDARY: string = '#0697FF'
export const GREY: string = '#666666'
export const BLACK: string = 'black'
export const SHADE: string = '#F0F0F0'
export const BLUE_SHADE: string = '#9ADDE6'
export const YELLOW: string = '#FFDC24'